ha=axes;
hca=get(ha, 'Children')
hc=allchild(ha)
get(hc(1), 'Visible')
get(hc, 'Type')
hc=allchild(ha)
set(hc(1), 'String', 'title')
ht=get(ha, 'Title');
set(ht, 'String', 'Title1')
get(hc, 'HandleVisability')
hc1=get(ha, 'Children')
set(0, 'ShowHiddenHandles', 'off')
hf=figure('HandleVisability', 'off')
hf=figure('HandleVisibility', 'off')
fplot(@sin, [0 3*pi])
set(2, 'Color', 'w')
hc=findall(hf)
hc=findall(hf, 'Type', 'patch', 'FaceColor', 'k')
set(hc, 'FaceColor', [0.8 0.8 0.8])