str='MATLAB хранит строки в виде вектор-строк'
substr='строк'
pos=findstr(str, substr)
str1='abc12345'
str2='abc12345'
rez=strcmp(str1, str2)
str2='ert456'
rez=strcmp(str1, str2)
str1='Hello, World'
str2='Hello, Igor'
rez=strcmp(str1, str2)
rez=strncmp(str1, str2, 5)
rez=strncmp(str1, str2, 9)
str='MATLAB 6.5 является последней версией пакета'
newstr=strrep(str, '6.5', '7.1')
str=upper(newstr)
str=lower(newstr)
rez=ischar(str)
rez=ischar(rez)